project:
  type: website

website:
  title: "Portafolio_test"
  navbar:
    logo: logo_maga.png
    logo-alt: "Magadiel - Inicio"
    title: false
    background: "#193B59"
    foreground: "#ffffff"
    left:
      - text: Home
        href: index.qmd
      - text: Proyectos
        href: projects/
      - text: Blog
        href: posts/
      - text: Libros
        href: books.qmd
      - text: Fotografias
        href: photography.qmd
      - text: Eventos
        href: events.qmd

    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - lux
      - brand
    css: styles.css

editor: visual

